apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: msa
    role: web
spec:
  replicas: 2
  selector:
    matchLabels:
      role: msa-web
  template:
    metadata:
      labels:
        app: msa
        role: msa-web
    spec:
      containers:
      - image: asia.gcr.io/architect-hslee/web:1580356494
        name: web
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: "10m"
            memory: "10Mi"
          limits:
            cpu: "20m"
            memory: "20Mi"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: msa
    role: apis
spec:
  replicas: 2
  selector:
    matchLabels:
      role: msa-api
  template:
    metadata:
      labels:
        app: msa
        role: msa-api
    spec:
      containers:
      - image: asia.gcr.io/architect-hslee/api:1580356460
        name: api
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: "10m"
            memory: "10Mi"
          limits:
            cpu: "20m"
            memory: "20Mi"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
  labels:
    app: msa
    role: posts
spec:
  replicas: 2
  selector:
    matchLabels:
      role: msa-post
  template:
    metadata:
      labels:
        app: msa
        role: msa-post
    spec:
      containers:
      - image: asia.gcr.io/architect-hslee/post:1580356468
        name: posts
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: "10m"
            memory: "10Mi"
          limits:
            cpu: "20m"
            memory: "20Mi"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: threads
  labels:
    app: msa
    role: threads
spec:
  replicas: 3
  selector:
    matchLabels:
      role: msa-thread
  template:
    metadata:
      labels:
        app: msa
        role: msa-thread
    spec:
      containers:
      - image: asia.gcr.io/architect-hslee/threads:1580356477
        name: threads
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: "10m"
            memory: "10Mi"
          limits:
            cpu: "20m"
            memory: "20Mi"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: msa
    role: users
spec:
  replicas: 2
  selector:
    matchLabels:
      role: msa-user
  template:
    metadata:
      labels:
        app: msa
        role: msa-user
    spec:
      containers:
      - image: asia.gcr.io/architect-hslee/users:1580356485
        name: users
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: "10m"
            memory: "10Mi"
          limits:
            cpu: "20m"
            memory: "20Mi"
