apiVersion: v1
kind: Service
metadata:
  name: monosvc
  labels:
    app: mono
    dev: mono-svc
spec:
  selector:
    app: mono
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
#  type: NodePort
